name = "SymbolTest"
uuid = "f6e3900e-0e5c-4d50-ae87-7ba54b61373f"
authors = ["Spencer Russell <spencer.russell@beacon.bio>"]
version = "0.1.0"

[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
