# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.3"
manifest_format = "2.0"

[[deps.Example]]
git-tree-sha1 = "46e44e869b4d90b96bd8ed1fdcf32244fddfb6cc"
uuid = "7876af07-990d-54b4-ab0e-23690620f79a"
version = "0.5.3"

[[deps.SymbolTest]]
deps = ["Example"]
path = ".."
uuid = "f6e3900e-0e5c-4d50-ae87-7ba54b61373f"
version = "0.1.0"
